apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker  # Match the label of the worker deployment
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 80   # Port the container listens on (update if needed)
  type: ClusterIP      # This exposes the service only inside the cluster
